on:
  push:
    branches:
    - main
    
jobs:
  build:
    name: Run Bash on commit, new file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Call a Bash Sript File from Main Directory
        run:  sh ./scripts/script.sh
