on:
  push:
    branches:
    - main
    
jobs:
  runscript:
    name: Run Bash on commit, new file
    runs-on: ubuntu-latest
    steps:
      - name: Call a Bash Script
        run:  echo "this be running new file"
