on:
  push:
    branches:
    - main
    
jobs:
  # this job contains single job called "build"
  build:
  
    run-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
      
      - name: Run one line script
        run: echo This is my new scipt
