on:
  push:
    branches:
    - main
    
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Run script file
      run: |
         chmod +x ./public/scripts/test.sh
         ./public/scripts/test.sh
      shell: bash
