on:
  push:
    branches:
    - main
    
jobs:
  runscript:
    name: Run Bash on commit
    runs-on: ubuntu-latest
    steps:
      - name: Call a Bash Script
        run:  |
         chmod +x ./scripts/test.sh
         ./scripts/test.sh
